# Stage 1: Build the Next.js/React app
FROM node:18-alpine AS build
WORKDIR /app

COPY package*.json .
RUN npm install

COPY src/app/ ./src/app/
COPY public/ ./public/
COPY src/middleware.js ./src/
COPY jsconfig.json .
COPY tailwind.config.js .
COPY postcss.config.js .
COPY next.config.mjs .

RUN npm run build

# Stage 2: Run the app
EXPOSE 3000
CMD ["npm", "run", "dev"]