# Stage 1: Build the Spring Boot application
FROM openjdk:21-slim AS build
WORKDIR /app

COPY .mvn/ .mvn/
COPY mvnw ./
COPY pom.xml ./
RUN chmod +x mvnw

RUN ./mvnw dependency:go-offline
COPY src/main/ ./src/main/
RUN ./mvnw clean package -DskipTests

# Stage 2: Run the Spring Boot application
FROM openjdk:21-slim AS backend
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]