import { Inter } from 'next/font/google';

import { Providers } from './providers';
import './styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en" className="h-full ">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <title>Quantum Library</title>
      </head>

      <body className={inter.className + ' h-full dark font-russo'} lang="es">
        <Providers>
          <div className="h-[9vh] bg-gray-800 flex gap-5 p-5 items-center align-bottom font-russo">
            <h1 className="font-faster-stroker text-4xl font-white uppercase "> Quantum Library </h1>
            <h2 className="text-2xl font-white"> | </h2>
            <h2 className="text-2xl font-white "> Explorar </h2>
            <h2 className="text-2xl font-white"> | </h2>
            <h2 className="text-2xl font-white "> Biblioteca </h2>
          </div>
          <div className="h-[91vh] overflow-hidden overflow-y-scroll bg-gray-900 font-russo">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
