name: Deploy Docker Compose to EC2

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Compilation and build
      - Tests
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd QuantumLibrary/
            
            git fetch origin
            git pull origin main

            echo "${{ secrets.DOCKER_COMPOSE_FILE }}" > docker-compose.yml
            
            docker images -q | xargs docker rmi -f
            docker-compose down
            docker-compose up -d
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
