name: Tests

on:
  push:
    branches: [ "Back/**", "Front/**"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run test
      run: mvn test
